name: Build and Deploy Solar System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_TEST_PASSWORD: ${{ secrets.MONGO_TEST_PASSWORD }}

  docker:
    name: docker
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

  dev-deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://${{ steps.getUrl.outputs.INGRESS_APP_URL }}
    outputs:
      APP_INGRESS_URL:  ${{ steps.getUrl.outputs.INGRESS_APP_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.1'
        id: install

#      - name: Install AWS CLI
#        run: |
#          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#          unzip awscliv2.zip
#          sudo ./aws/install --update
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWSACCOUNTID }}
#          aws-secret-access-key: ${{ secrets.AWSSECRET }}
#          aws-region: us-east-1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}


      #      - name: Update kubeconfig for EKS
#        run: |
#          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name ${{ vars.KUBE_CLUSTER }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Fetch Kube Details
        run: |
          kubectl version
          echo -----------------------
          kubectl get nodes

      - name: Get Kube LoadBalancer HostName
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace Tokens In Manifest Files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check Files
        run: |
          cat kubernetes/development/*.yaml

      - name: Create Mongo Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
          --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
          --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy To DEV
        run: |
          kubectl apply -f kubernetes/development

      - name: Get URL
        id: getUrl
        run: |
          echo "INGRESS_APP_URL=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT
          echo "-------------------------------"
          echo $INGRESS_APP_URL

  dev-integration-test:
    name: Development Integration Testing
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test Application Using Curl
        env:
          URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
        run: |
          echo ${{ env.URL }}
          echo "-------------------------"
          curl https://${{ env.URL }}/live -s -k | jq -r .status | grep -i "live"

#  prod-deploy:
#    needs: dev-integration-test
#    runs-on: ubuntu-latest
#    environment:
#      name: production
#      url: https://${{ steps.getUrl.outputs.INGRESS_APP_URL }}
#    outputs:
#      APP_INGRESS_URL:  ${{ steps.getUrl.outputs.INGRESS_APP_URL }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: install kubectl
#        uses: azure/setup-kubectl@v4
#        with:
#          version: 'v1.31.1'
#        id: install
#
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
#
#      - name: Save DigitalOcean kubeconfig
#        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
#
#      - name: Fetch Kube Details
#        run: |
#          kubectl version
#          echo -----------------------
#          kubectl get nodes
#
#      - name: Get Kube LoadBalancer HostName
#        run: |
#          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
#
#      - name: Replace Tokens In Manifest Files
#        uses: cschleiden/replace-tokens@v1
#        with:
#          tokenPrefix: '_{_'
#          tokenSuffix: '_}_'
#          files: '["kubernetes/production/*.yaml"]'
#        env:
#          NAMESPACE: ${{ vars.NAMESPACE }}
#          REPLICAS: ${{ vars.REPLICAS }}
#          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
#          INGRESS_IP: ${{ env.INGRESS_IP }}
#
#      - name: Check Files
#        run: |
#          cat kubernetes/production/*.yaml
#
#      - name: Create Mongo Secret
#        run: |
#          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
#          --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
#          --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
#          --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
#          --dry-run=client -o yaml | kubectl apply -f -
#
#      - name: Deploy To DEV
#        run: |
#          kubectl apply -f kubernetes/production
#
#      - name: Get URL
#        id: getUrl
#        run: |
#          echo "INGRESS_APP_URL=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT
#          echo "-------------------------------"
#          echo $INGRESS_APP_URL
#
#  prod-integration-test:
#    name: Production Integration Testing
#    needs: prod-deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Test Application Using Curl
#        env:
#          URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL }}
#        run: |
#          echo ${{ env.URL }}
#          echo "-------------------------"
#          curl https://${{ env.URL }}/live -s -k | jq -r .status | grep -i "live"
